### ISSUE TITLE
Question about the stereo depth

### ISSUE THREAD

**Issue by jiaxiZeng** [sadrasafa/StereoGS#2]
Thanks for your excellent work! I have a question about the motivation of using the depth from the rendered stereo pair as the GS depth loss.  Theoretically, the rendered right view reflects the underlying geometry of Gaussians, but why does the stereo depth get the better geometry than the GS depth? Can you explain the intuition about it？

**Comment by sadra-safa** [comment]
The intuition is that although the rendered depth is not accurate, the rendered images are accurate, and the rendered left and right images are actually geometrically consistent. Therefore calculating the depth through a stereo method gives more accurate results than rendering depth from Gaussians.

**Comment by sadrasafa** [comment]
The intuition is that although the rendered depth is not accurate, the rendered images are accurate, and the rendered left and right images are actually geometrically consistent. Therefore calculating the depth through a stereo method gives more accurate results than rendering depth from Gaussians.
